# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-03 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=48, unique=True),
        ),
    ]
